### ISSUE TITLE
'Message' object has no attribute 'replace'

### ISSUE THREAD

**Issue by matteuscruz** [ThisIs-Developer/Llama-2-GGML-Medical-Chatbot#9] opened 2024-01-10 16:58 UTC
The last command "chainlit run model.py -w" starts the model well, but when I put the first line to start the conversation I get the following message "'Message' object has no attribute 'replace'" and the terminal presents the following error: 

2024-01-10 13:51:38 - 'Message' object has no attribute 'replace'
Traceback (most recent call last):
  File "/chatbot-venv/lib/python3.11/site-packages/chainlit/utils.py", line 39, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/model.py", line 86, in main
    res = await chain.acall(message, callbacks=[cb])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/chains/base.py", line 361, in acall
    raise e
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/chains/base.py", line 355, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 179, in _acall
    docs = await self._aget_docs(question, run_manager=_run_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteuscruz/Desktop/PrecisionCare/medical_chatbot_web/chatbot-venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 227, in _aget_docs
    return await self.retriever.aget_relevant_documents(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/schema/retriever.py", line 264, in aget_relevant_documents
    raise e
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/schema/retriever.py", line 257, in aget_relevant_documents
    result = await self._aget_relevant_documents(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/medical_chatbot_web/chatbot-venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 582, in _aget_relevant_documents
    docs = await self.vectorstore.asimilarity_search(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 294, in asimilarity_search
    return await asyncio.get_event_loop().run_in_executor(None, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/usr/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/medical_chatbot_web/chatbot-venv/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 334, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 275, in similarity_search_with_score
    embedding = self.embedding_function(query)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 103, in embed_query
    return self.embed_documents([text])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 84, in embed_documents
    texts = list(map(lambda x: x.replace("\n", " "), texts))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/chatbot-venv/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 84, in <lambda>
    texts = list(map(lambda x: x.replace("\n", " "), texts))
                               ^^^^^^^^^
AttributeError: 'Message' object has no attribute 'replace'

**Comment by ThisIs-Developer** [comment] 2024-01-11 14:50
Thanks for bringing this up!

It looks like the issue is resolved by changing res = await chain.acall(message, callbacks=[cb]) to res = await chain.acall(message.content, callbacks=[cb]) in line 86. Now we are **passing only the content attribute of the message object to acall**.

It works!👍

![Screenshot 2024-01-11 181157](https://github.com/ThisIs-Developer/Llama-2-GGML-Medical-Chatbot/assets/109382325/62541ad6-84bd-4327-ac44-78e827e6e46f)

**Closed** 2024-01-11 14:52 UTC
Labels: bug
